server:
  port: 8771
  #  servlet:
  #    context-path: /register
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

logging:
  level:
    root: INFO
  file:
    name: logs/register.log

spring:
  data:
    redis:
      #      host: 192.168.109.222
      host: 127.0.0.1
      port: 6379
      password: LUIcYikvVg6i4pV
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-idle: 10
          min-idle: 0
          max-wait: 10000
  datasource:
    dynamic:
      primary: k5
      strict: false
      datasource:
        k5:
          url: jdbc:sqlserver://rm-bp1085gt89v6u0ms7so.sqlserver.rds.aliyuncs.com:1433;databaseName=k5;encrypt=true;trustServerCertificate=true;loginTimeout=30;
          username: XH
          password: Passw0rd
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        t6:
          url: jdbc:sqlserver://rm-bp1085gt89v6u0ms7so.sqlserver.rds.aliyuncs.com:1433;databaseName=t6new;encrypt=true;trustServerCertificate=true;loginTimeout=30;
          username: XH
          password: Passw0rd
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    jpa:
  #      hibernate:
  #        ddl-auto: update
  #      show-sql: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

knife4j:
  enable: false
  basic:
    username: admin
    password: 123123
    enable: true
  setting:
    language: zh_cn
    enable-footer: true
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2019-[XIHE](https://www.baidu.com)